### PR TITLE
fix guess_types bug

### PR DESCRIPTION
**Pull request by wang19930902**

### CODE REVIEW

**Comment by saily** [comment]
What's missing to get this merged?

**Comment by saily** [comment]
@wichert ping

**Comment by wichert** [comment]
Can you explain what bug this is solving?

**Comment by saily** [comment]
fixes #5

**Comment by wichert** [comment]
Looks like that broke due to [this change](https://bitbucket.org/openpyxl/openpyxl/commits/2408b45757b5a363fd1a5985885e1bc44a25663b?at=default) in OpenPyxl.

**Pull request merged**
