### PR TITLE
Allow to Ignore sheets.

### LINKED ISSUE #14: Allow to ignore specific sheets
It would be nice to allow `xls-to-po` to skip processing specific sheets. 

We have an use case where we use spreadsheets and formulas are used to autocomplete translations. And we would want to ignore those sheets from the export process.

### PR DESCRIPTION
**Pull request by mariano-dagostino**
Fixes  #14

### CODE REVIEW

**Comment by wichert** [comment]
Hi Mariano,

instead of specifying the sheet index, wouldn't it be more natural to specify the sheet name? I'm sure there will be some confusion about numbering starting at 0 or 1 otherwise, and it would protect against reordering.

**Comment by mariano-dagostino** [comment]
@wichert Thanks for the quick response.

Yes, I was trying to decide what option was best. Sheet names makes the command look longer. But I guess is safer to go with names instead of IDs.

**Comment by mariano-dagostino** [comment]
@wichert Thanks for the quick response.

Yes, I was trying to decide what option was best. Sheet names makes the command look longer. But I guess is safer to go with names instead of IDs. I updated the PR.

**Comment by mariano-dagostino** [comment]
@wichert Hi! just checking this. I updated the PR to use tabs names instead of IDs. Could you review the code when you have some time? Thanks!

**Pull request merged**
